[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pump_fun_sp = "81Pjgpp9Q8zjQrNqtVDjjzTLK4U568u1UAmN5WoRXb5m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/peace/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
